# All actions used in this action run on the latest version.
- name: Publish artifacts
  runs-on: ubuntu-latest

on:
 [release]
jobs:
  publish:
    steps:
     - name: Checkout
       uses: actions/checkout@latest
  
     - name: Cache old artifact
       uses: actions/cache@latest
     - name: Upload to GH Actions
       uses: actions/upload-artifact@latest
