# All actions used in this action run on v2.(latest) and are official github actions.
- name: Publish artifacts
  runs-on: ubuntu-latest

on:
 release
   type:
    [published]
jobs:
  publish:
    steps:
     - name: Checkout
       uses: actions/checkout@v2
  
     - name: Cache old artifact
       uses: actions/cache@v2
     - name: Upload to GH Actions
       uses: actions/upload-artifact@v2
